spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - TRACE
              - PATCH
              - OPTIONS
              - CONNECT
      discovery:
        locator:
          enabled: true
      routes:
        - id: 163
          uri: http://www.baidu.com
          predicates:
            - Path=/push/**
          filters:
            - StripPrefix=1
        - id: lobby-server
          uri: lb://LOBBY-SERVER
          predicates:
            - Path=/lobby/**
          filters:
            - name: Token
            - StripPrefix=1
server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 15  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    ip: 127.0.0.1:7000
    registry-fetch-interval-seconds: 5 # 拉取服务注册信息间隔（缺省为30s）
    service-url:
      defaultZone: http://${eureka.client.ip}/eureka/
    healthcheck:
      enabled: true # 开启健康检查（依赖spring-boot-starter-actuator）